# aws-greengrass-system-log-forwarder - AWS Greengrass component for forwarding
# logs to CloudWatch.
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
RecipeFormatVersion: "2020-01-25"
ComponentName: "aws.greengrass.SystemLogForwarder"
ComponentVersion: "0.1.0"
ComponentDescription: AWS Greengrass System Log Forwarder
ComponentPublisher: AWS
ComponentConfiguration:
  DefaultConfiguration:
    "maxUploadIntervalSec": 300
    "maxRetriesCount": 3
    "bufferCapacity": 1048576
    "logGroup": "greengrass/systemLogs"
    "aws-region": "us-west-2"
Manifests:
  - Platform:
      os: linux
      runtime: "*"
    Lifecycle:
      run: |
        {artifacts:path}/system-log-forwarder --maxUploadIntervalSec {configuration:/maxUploadIntervalSec} --maxRetriesCount {configuration:/maxRetriesCount} --bufferCapacity {configuration:/bufferCapacity} --logGroup {configuration:/logGroup} --thingName {iot:thingName} --region {configuration:/aws-region}
