# aws-greengrass-system-log-forwarder - AWS Greengrass component for forwarding
# logs to CloudWatch.
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
RecipeFormatVersion: "2020-01-25"
ComponentName: "aws.greengrass.SystemLogForwarder"
ComponentVersion: "0.1.0"
ComponentDescription: AWS Greengrass System Log Forwarder
ComponentPublisher: AWS
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        aws.greengrass.CloudLogger:mqttproxy:1:
          policyDescription: Allows access to publish/subscribe to all topics.
          operations:
            - aws.greengrass#PublishToIoTCore
          resources:
            - "gglite/+/logs"
Manifests:
  - Platform:
      os: linux
      runtime: "*"
    Lifecycle:
      run: |
        {artifacts:path}/cloud-logger
