name: Build and Package SystemLogForwarder

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config git libssl-dev

      - name: Set version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_OUTPUT

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DGGL_LOG_LEVEL=INFO

      - name: Build
        run: make -C build -j$(nproc)

      - name: Strip binary
        run: strip build/bin/system-log-forwarder

      - name: Create package
        run: |
          mkdir -p ${{ github.workspace }}/zipfile
          zip -9 ${{ github.workspace }}/zipfile/system-log-forwarder-${{ matrix.arch }}-${{ steps.version.outputs.VERSION }}.zip -j build/bin/system-log-forwarder

      - name: md5sums
        run: |
          md5sum ${{ github.workspace }}/zipfile/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name:
            system-log-forwarder-${{ matrix.arch }}-${{
            steps.version.outputs.VERSION }}
          path: |
            ${{ github.workspace }}/zipfile/*
          retention-days: 1
